[workspace]
members = ["crates/*", "bin/*"]
resolver = "3"

[workspace.dependencies]
dotenvy = "0.15.7"
eyre = "0.6.12"
color-eyre = "0.6.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "json"
] }
thiserror = "2.0.19"
bon = "3.9.3"
topcoat = { version = "0.6.0", features = ["tower"] }
axum = "0.8.4"
tokio = { version = "1.53.1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
  "time"
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["v7", "serde"] }
url = "2.5.8"
validator = { version = "0.19.0", default-features = false }
time = { version = "0.3.54", features = ["serde", "formatting", "parsing"] }
chrono = { version = "0.4.41", features = ["serde"] }
sqlx = { version = "0.8.6", default-features = false, features = [
  "runtime-tokio-rustls",
  "chrono",
  "uuid",
  "time",
  "json",
  "postgres",
  "macros",
  "migrate"
] }
better-auth = { version = "=0.10.0", default-features = false, features = [
  "axum",
  "sqlx-postgres",
  "rustls"
] }
