[workspace]
members = ["crates/*", "bin/*"]
resolver = "3"

[workspace.dependencies]
eyre = "0.6.12"
color-eyre = "0.6.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "json"
] }
thiserror = "2.0.19"
bon = "3.9.3"
topcoat = "0.5.0"
tokio = { version = "1.53.1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
  "time"
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["v7", "serde"] }
time = { version = "0.3.54", features = ["serde", "formatting", "parsing"] }
sqlx = { version = "0.9.0", default-features = false, features = [
  "tls-rustls",
  "uuid",
  "runtime-tokio",
  "time",
  "json",
  "postgres",
  "macros",
  "migrate"
] }
