[package]
name = "launchlightly-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
better-auth.workspace = true
chrono.workspace = true
launchlightly-infra-postgresql = { path = "../infra-postgresql" }
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
topcoat = { workspace = true, features = ["font-fontsource", "icon-iconify", "tailwind", "ui"] }
url.workspace = true

[build-dependencies]
topcoat = { version = "0.6.0", default-features = false, features = ["icon-iconify", "tailwind"] }

[dev-dependencies]
tokio.workspace = true
